import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/Navbar/index'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Gabriel Leão | portfólio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.png" />
      </Head>
      
      <Navbar />
    </div>
  )
}

export default Home
